-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 LaconisIves
--
-- Code generated by testkit/lua/generate_catalog.py; DO NOT EDIT.
-- Verdandi Catalog replace script.
--
-- KEYS[1]: verdandi:catalog:<zone>:@meta
-- KEYS[2]: verdandi:catalog:<zone>:@live
-- KEYS[3]: verdandi:catalog:<zone>:@deleted
-- KEYS[4]: verdandi:catalog:<zone>:@deleted_time
-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>
-- KEYS[6]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions
-- ARGV: path-member, kind, encoded_bytes, field_count, field/value pairs.
--
-- SDKs own application encoding, path and shape validation, capacity
-- projection, and notification decoding. Lua only joins current-state
-- preconditions with an accepted mutation or read snapshot atomically.

-- BEGIN common/bindings.lua.inc
local redis_call = redis.call

local function redis_type(key)
    local result = redis_call("TYPE", key)
    if type(result) == "table" then
        return result.ok
    end
    return result
end

local function error_reply(status, field, revision)
    local result = { "&result", "error", "&status", status }
    if field then
        result[#result + 1] = "&field"
        result[#result + 1] = field
    end
    if revision then
        result[#result + 1] = "@revision"
        result[#result + 1] = revision
    end
    return result
end
-- END common/bindings.lua.inc

-- BEGIN common/integer.lua.inc
local maximum_revision = "9007199254740991"
local maximum_encoded_bytes = 4194304
local maximum_fields = 65536

local function canonical_nonnegative(value)
    if value == "0" then
        return true
    end
    if not value or not string.match(value, "^[1-9][0-9]*$") then
        return false
    end
    return #value < #maximum_revision or
        (#value == #maximum_revision and value <= maximum_revision)
end

local function canonical_positive(value)
    return value ~= "0" and canonical_nonnegative(value)
end

local function decimal_less(left, right)
    if #left ~= #right then
        return #left < #right
    end
    return left < right
end

local function increment_decimal(value)
    local length = #value
    local index = length
    while index > 0 and string.byte(value, index) == 57 do
        index = index - 1
    end
    if index == 0 then
        return "1" .. string.rep("0", length)
    end
    return string.sub(value, 1, index - 1) ..
        string.char(string.byte(value, index) + 1) ..
        string.rep("0", length - index)
end

local function canonical_count(value, maximum)
    if value ~= "0" and
        (not value or not string.match(value, "^[1-9][0-9]*$")) then
        return nil
    end
    local result = tonumber(value)
    if not result or result > maximum or result % 1 ~= 0 then
        return nil
    end
    return result
end
-- END common/integer.lua.inc

-- BEGIN common/state.lua.inc
local meta_key = KEYS[1]
local live_key = KEYS[2]
local deleted_key = KEYS[3]
local deleted_time_key = KEYS[4]
local catalog_key = KEYS[5]
local field_revisions_key = KEYS[6]
local member = ARGV[1]

if #KEYS ~= 6 or #ARGV < 1 or not member or member == "" then
    return error_reply("contract")
end

local fail = error_reply

local meta_type = redis_type(meta_key)
local live_type = redis_type(live_key)
local deleted_type = redis_type(deleted_key)
local deleted_time_type = redis_type(deleted_time_key)
local catalog_type = redis_type(catalog_key)
local field_revision_type = redis_type(field_revisions_key)
if (meta_type ~= "none" and meta_type ~= "hash") or
    (live_type ~= "none" and live_type ~= "zset") or
    (deleted_type ~= "none" and deleted_type ~= "zset") or
    (deleted_time_type ~= "none" and deleted_time_type ~= "zset") or
    (catalog_type ~= "none" and catalog_type ~= "hash") or
    (field_revision_type ~= "none" and field_revision_type ~= "zset") then
    return fail("corrupt")
end

local meta = redis_call("HMGET", meta_key, "@revision", "@floor_revision")
local global_revision = meta[1]
local floor_revision = meta[2]
if not global_revision then
    if floor_revision or redis_call("HLEN", meta_key) ~= 0 or
        redis_call("ZCARD", live_key) ~= 0 or
        redis_call("ZCARD", deleted_key) ~= 0 or
        redis_call("ZCARD", deleted_time_key) ~= 0 then
        return fail("corrupt")
    end
    global_revision = "0"
    floor_revision = "0"
elseif not canonical_positive(global_revision) or
    not canonical_nonnegative(floor_revision) or
    decimal_less(global_revision, floor_revision) then
    return fail("corrupt")
end

local live_revision = redis_call("ZSCORE", live_key, member)
local deleted_revision = redis_call("ZSCORE", deleted_key, member)
local deleted_time = redis_call("ZSCORE", deleted_time_key, member)
if (live_revision and deleted_revision) or
    ((deleted_revision and not deleted_time) or
        (deleted_time and not deleted_revision)) or
    (live_revision and not canonical_positive(live_revision)) or
    (deleted_revision and not canonical_positive(deleted_revision)) or
    (deleted_time and not canonical_nonnegative(deleted_time)) then
    return fail("corrupt")
end

local current_revision = "0"
local current_kind = nil
local current_encoded_bytes = "0"
local current_replace_revision = "0"

if catalog_type == "hash" then
    if not live_revision or deleted_revision then
        return fail("corrupt")
    end
    local header = redis_call(
        "HMGET", catalog_key,
        "@revision", "@replace_revision", "@kind", "@encoded_bytes"
    )
    current_revision = header[1]
    current_replace_revision = header[2]
    current_kind = header[3]
    current_encoded_bytes = header[4]
    if not canonical_positive(current_revision) or
        not canonical_positive(current_replace_revision) or
        decimal_less(current_revision, current_replace_revision) or
        (current_kind ~= "value" and current_kind ~= "array" and
            current_kind ~= "map") or
        not canonical_nonnegative(current_encoded_bytes) or
        tonumber(current_encoded_bytes) > maximum_encoded_bytes or
        live_revision ~= current_revision then
        return fail("corrupt")
    end
    if field_revision_type == "none" and redis_call("HLEN", catalog_key) ~= 4 then
        return fail("corrupt")
    end
elseif live_revision or field_revision_type == "zset" then
    return fail("corrupt")
elseif deleted_revision then
    current_revision = deleted_revision
end

if decimal_less(global_revision, current_revision) then
    return fail("corrupt")
end
-- END common/state.lua.inc

-- BEGIN actions/replace.lua.inc
local kind = ARGV[2]
local encoded_bytes_text = ARGV[3]
local field_count_text = ARGV[4]
local field_count = canonical_count(field_count_text, maximum_fields)
local encoded_bytes = canonical_count(encoded_bytes_text, maximum_encoded_bytes)
if #ARGV < 4 or not field_count or not encoded_bytes or
    #ARGV ~= 4 + field_count * 2 or
    (kind ~= "value" and kind ~= "array" and kind ~= "map") or
    (kind == "value" and field_count ~= 1) then
    return fail("contract")
end

local first_field = 5
local calculated_bytes = 0
local previous_name = nil
for index = 0, field_count - 1 do
    local name = ARGV[first_field + index * 2]
    local value = ARGV[first_field + index * 2 + 1]
    if not name or name == "" or string.sub(name, 1, 1) == "@" or not value then
        return fail("contract")
    end
    if kind == "value" then
        if name ~= "value" then
            return fail("contract")
        end
    elseif kind == "array" then
        if name ~= tostring(index) then
            return fail("contract")
        end
    elseif previous_name and previous_name >= name then
        return fail("contract")
    end
    previous_name = name
    calculated_bytes = calculated_bytes + #name + #value
end
if calculated_bytes ~= encoded_bytes then
    return fail("contract", "@encoded_bytes")
end
if global_revision == maximum_revision then
    return fail("capacity", "@revision")
end

local next_revision = increment_decimal(global_revision)
local command_chunk_fields = 1024
redis_call("UNLINK", catalog_key, field_revisions_key)
redis_call(
    "HSET", catalog_key,
    "@revision", next_revision,
    "@replace_revision", next_revision,
    "@kind", kind,
    "@encoded_bytes", encoded_bytes_text
)
for first = 0, field_count - 1, command_chunk_fields do
    local last = math.min(first + command_chunk_fields - 1, field_count - 1)
    redis_call(
        "HSET", catalog_key,
        unpack(ARGV, first_field + first * 2, first_field + last * 2 + 1)
    )
    local revisions = {}
    for index = first, last do
        revisions[#revisions + 1] = next_revision
        revisions[#revisions + 1] = ARGV[first_field + index * 2]
    end
    redis_call("ZADD", field_revisions_key, unpack(revisions))
end

redis_call("HSET", meta_key, "@revision", next_revision,
    "@floor_revision", floor_revision)
redis_call("ZADD", live_key, next_revision, member)
redis_call("ZREM", deleted_key, member)
redis_call("ZREM", deleted_time_key, member)

local fields = {}
for index = 0, field_count - 1 do
    fields[index * 2 + 1] = ARGV[first_field + index * 2]
    fields[index * 2 + 2] = ARGV[first_field + index * 2 + 1]
end
redis_call("PUBLISH", catalog_key, cmsgpack.pack({
    "v1", "replace", member, next_revision, kind, encoded_bytes_text, fields
}))
return {
    "&result", "ok",
    "@revision", next_revision,
    "@floor_revision", floor_revision,
}
-- END actions/replace.lua.inc

