#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 LaconisIves

"""Generate deterministic operation-specific Registration Lua scripts."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
import tempfile
from typing import Iterable

ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = ROOT / "lua" / "src" / "registration"
MANIFEST = SOURCE_ROOT / "manifest.json"
KINDS = ("register", "update", "renew", "unregister")
ARGUMENT_LAYOUTS = {
    "register": ("-- ARGV[1..4]：uuid、revision、ttl_ms、version；" "ARGV[5..]：Attr/Data 字段名和值的有序键值对。\n"),
    "update": ("-- ARGV[1..3]：uuid、revision、version（不修改时为空）；" "ARGV[4..]：Data 字段名和值的有序键值对。\n"),
    "renew": "-- ARGV[1..2]：uuid、当前 revision。\n",
    "unregister": "-- ARGV[1]：uuid。\n",
}
OUTPUT_ROOTS = (
    ROOT / "lua" / "registration",
    ROOT / "sdk" / "go" / "registration" / "internal" / "protocol",
    ROOT / "sdk" / "rust" / "src" / "registration",
    ROOT / "sdk" / "cpp" / "src" / "protocol" / "registration",
)


def load_manifest() -> dict[str, list[str]]:
    raw = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or tuple(raw) != KINDS:
        raise ValueError(f"manifest operations must be exactly {KINDS!r} in order")

    manifest: dict[str, list[str]] = {}
    referenced: set[str] = set()
    for kind, fragments in raw.items():
        if not isinstance(fragments, list) or not fragments:
            raise ValueError(f"{kind}: fragments must be a non-empty list")
        if len(fragments) != len(set(fragments)):
            raise ValueError(f"{kind}: duplicate fragment")
        for fragment in fragments:
            if not isinstance(fragment, str):
                raise ValueError(f"{kind}: fragment path must be a string")
            path = Path(fragment)
            if path.is_absolute() or ".." in path.parts:
                raise ValueError(f"{kind}: unsafe fragment path {fragment!r}")
        actions = [fragment for fragment in fragments if fragment.startswith("actions/")]
        if actions != [f"actions/{kind}.lua.inc"] or fragments[-1] != actions[0]:
            raise ValueError(f"{kind}: its action fragment must be the final fragment")
        if any(not fragment.startswith(("common/", "actions/")) for fragment in fragments):
            raise ValueError(f"{kind}: fragment must belong to common/ or actions/")
        manifest[kind] = fragments
        referenced.update(fragments)

    available = {path.relative_to(SOURCE_ROOT).as_posix() for path in SOURCE_ROOT.rglob("*.lua.inc")}
    if referenced != available:
        missing = sorted(referenced - available)
        unused = sorted(available - referenced)
        raise ValueError(f"manifest mismatch: missing={missing!r}, unused={unused!r}")
    return manifest


def read_fragment(relative: str) -> str:
    path = SOURCE_ROOT / relative
    raw = path.read_bytes()
    if b"\r" in raw:
        raise ValueError(f"{relative}: CR bytes are not canonical")
    text = raw.decode("utf-8")
    if not text.endswith("\n"):
        raise ValueError(f"{relative}: fragment must end with LF")
    return text


def generate(kind: str, fragments: Iterable[str]) -> str:
    lines = [
        "-- SPDX-License-Identifier: MIT\n",
        "-- Copyright (c) 2026 LaconisIves\n",
        "--\n",
        "-- Code generated by testkit/lua/generate_registration.py; DO NOT EDIT.\n",
        f"-- Verdandi Registration {kind} script.\n",
        "--\n",
        "-- KEYS[1]：verdandi:registration:<zone>:<type>:<uuid>，保存完整 Registration Hash。\n",
        "-- KEYS[2]：verdandi:registry:<zone>:<type>，同时作为成员索引 Hash 和事件频道。\n",
        ARGUMENT_LAYOUTS[kind],
        "--\n",
        "-- SDK 负责请求校验和应用数据解码；脚本只把一次已校验的 Registration 操作\n",
        "-- 粘合为一次 Redis 原子变更。Attr 和 Data 字节对 Redis/Lua 始终不透明。\n",
        "\n",
    ]
    for relative in fragments:
        lines.append(f"-- BEGIN {relative}\n")
        lines.append(read_fragment(relative))
        lines.append(f"-- END {relative}\n\n")
    return "".join(lines)


def expected_outputs(manifest: dict[str, list[str]]) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for kind in KINDS:
        source = generate(kind, manifest[kind])
        for root in OUTPUT_ROOTS:
            outputs[root / f"{kind}.lua"] = source
    return outputs


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
            output.write(content)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def check(outputs: dict[Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_bytes()
        except FileNotFoundError:
            stale.append(path)
            continue
        if actual != expected.encode("utf-8"):
            stale.append(path)

    expected_paths = set(outputs)
    for root in OUTPUT_ROOTS:
        if root.exists():
            stale.extend(path for path in root.glob("*.lua") if path not in expected_paths)

    if stale:
        for path in sorted(set(stale)):
            print(f"stale generated Lua: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    print("Registration Lua generated files are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files instead of writing them",
    )
    arguments = parser.parse_args()

    outputs = expected_outputs(load_manifest())
    if arguments.check:
        return check(outputs)
    for path, content in outputs.items():
        if not path.exists() or path.read_bytes() != content.encode("utf-8"):
            atomic_write(path, content)
            print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
