#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 LaconisIves

"""Generate deterministic operation-specific Catalog Lua scripts."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
import tempfile
from typing import Iterable

ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = ROOT / "lua" / "src" / "catalog"
MANIFEST = SOURCE_ROOT / "manifest.json"
KINDS = ("read", "replace", "patch", "delete")
KEY_LAYOUTS = {
    "read": (
        "-- KEYS[1]: verdandi:catalog:<zone>:@live\n"
        "-- KEYS[2]: verdandi:catalog:<zone>:@deleted\n"
        "-- KEYS[3]: verdandi:catalog:<zone>:@deleted_time\n"
        "-- KEYS[4]: verdandi:catalog:<zone>:<part>:<id>\n"
        "-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions\n"
    ),
    "replace": (
        "-- KEYS[1]: verdandi:catalog:<zone>:@meta\n"
        "-- KEYS[2]: verdandi:catalog:<zone>:@live\n"
        "-- KEYS[3]: verdandi:catalog:<zone>:@deleted\n"
        "-- KEYS[4]: verdandi:catalog:<zone>:@deleted_time\n"
        "-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>\n"
        "-- KEYS[6]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions\n"
    ),
    "patch": (
        "-- KEYS[1]: verdandi:catalog:<zone>:@meta\n"
        "-- KEYS[2]: verdandi:catalog:<zone>:@live\n"
        "-- KEYS[3]: verdandi:catalog:<zone>:@deleted\n"
        "-- KEYS[4]: verdandi:catalog:<zone>:@deleted_time\n"
        "-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>\n"
        "-- KEYS[6]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions\n"
    ),
    "delete": (
        "-- KEYS[1]: verdandi:catalog:<zone>:@meta\n"
        "-- KEYS[2]: verdandi:catalog:<zone>:@live\n"
        "-- KEYS[3]: verdandi:catalog:<zone>:@deleted\n"
        "-- KEYS[4]: verdandi:catalog:<zone>:@deleted_time\n"
        "-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>\n"
        "-- KEYS[6]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions\n"
    ),
}
ARGUMENT_LAYOUTS = {
    "read": "-- ARGV: path-member, local-present-revision-or-zero.\n",
    "replace": ("-- ARGV: path-member, kind, encoded_bytes, field_count, " "field/value pairs.\n"),
    "patch": ("-- ARGV: path-member, base_revision, encoded_bytes, " "set_count, field/value pairs.\n"),
    "delete": "-- ARGV: path-member.\n",
}
OUTPUT_ROOTS = (
    ROOT / "lua" / "catalog",
    ROOT / "sdk" / "go" / "catalog" / "internal" / "protocol",
    ROOT / "sdk" / "rust" / "src" / "catalog" / "protocol",
    ROOT / "sdk" / "cpp" / "src" / "protocol" / "catalog",
)


def load_manifest() -> dict[str, list[str]]:
    raw = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or tuple(raw) != KINDS:
        raise ValueError(f"manifest operations must be exactly {KINDS!r} in order")
    manifest: dict[str, list[str]] = {}
    referenced: set[str] = set()
    for kind, fragments in raw.items():
        if not isinstance(fragments, list) or not fragments:
            raise ValueError(f"{kind}: fragments must be a non-empty list")
        if len(fragments) != len(set(fragments)):
            raise ValueError(f"{kind}: duplicate fragment")
        for fragment in fragments:
            if not isinstance(fragment, str):
                raise ValueError(f"{kind}: unsafe fragment path {fragment!r}")
            path = Path(fragment)
            if path.is_absolute() or ".." in path.parts:
                raise ValueError(f"{kind}: unsafe fragment path {fragment!r}")
        action = f"actions/{kind}.lua.inc"
        if fragments[-1] != action or fragments.count(action) != 1:
            raise ValueError(f"{kind}: its action fragment must be final")
        manifest[kind] = fragments
        referenced.update(fragments)
    available = {path.relative_to(SOURCE_ROOT).as_posix() for path in SOURCE_ROOT.rglob("*.lua.inc")}
    if referenced != available:
        raise ValueError(f"manifest mismatch: missing={sorted(referenced - available)!r}, " f"unused={sorted(available - referenced)!r}")
    return manifest


def read_fragment(relative: str) -> str:
    raw = (SOURCE_ROOT / relative).read_bytes()
    if b"\r" in raw:
        raise ValueError(f"{relative}: CR bytes are not canonical")
    text = raw.decode("utf-8")
    if not text.endswith("\n"):
        raise ValueError(f"{relative}: fragment must end with LF")
    return text


def generate(kind: str, fragments: Iterable[str]) -> str:
    lines = [
        "-- SPDX-License-Identifier: MIT\n",
        "-- Copyright (c) 2026 LaconisIves\n",
        "--\n",
        "-- Code generated by testkit/lua/generate_catalog.py; DO NOT EDIT.\n",
        f"-- Verdandi Catalog {kind} script.\n",
        "--\n",
        KEY_LAYOUTS[kind],
        ARGUMENT_LAYOUTS[kind],
        "--\n",
        "-- SDKs own application encoding, path and shape validation, capacity\n",
        "-- projection, and notification decoding. Lua only joins current-state\n",
        "-- preconditions with an accepted mutation or read snapshot atomically.\n",
        "\n",
    ]
    for relative in fragments:
        lines.extend(
            [
                f"-- BEGIN {relative}\n",
                read_fragment(relative),
                f"-- END {relative}\n\n",
            ]
        )
    return "".join(lines)


def expected_outputs(manifest: dict[str, list[str]]) -> dict[Path, str]:
    return {root / f"{kind}.lua": generate(kind, manifest[kind]) for kind in KINDS for root in OUTPUT_ROOTS}


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
            output.write(content)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def check(outputs: dict[Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_bytes()
        except FileNotFoundError:
            stale.append(path)
            continue
        if actual != expected.encode("utf-8"):
            stale.append(path)
    expected_paths = set(outputs)
    for root in OUTPUT_ROOTS:
        if root.exists():
            stale.extend(path for path in root.glob("*.lua") if path not in expected_paths)
    if stale:
        for path in sorted(set(stale)):
            print(f"stale generated Lua: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    print("Catalog Lua generated files are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    outputs = expected_outputs(load_manifest())
    if arguments.check:
        return check(outputs)
    expected_paths = set(outputs)
    for root in OUTPUT_ROOTS:
        if root.exists():
            for path in root.glob("*.lua"):
                if path not in expected_paths:
                    path.unlink()
                    print(f"removed {path.relative_to(ROOT)}")
    for path, content in outputs.items():
        if not path.exists() or path.read_bytes() != content.encode("utf-8"):
            atomic_write(path, content)
            print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
