# 只消费已经获得的官方 amalgamation. 配置阶段不下载, 不查找系统 SQLite 或接受其他版本.
set(ASTRA_SQLITE_ARCHIVE "${CMAKE_CURRENT_SOURCE_DIR}/../build/deps/common/downloads/fetchcontent/sqlite/sqlite-amalgamation-3530400.zip" CACHE FILEPATH "Existing SQLite 3.53.4 amalgamation archive")
set(star_sqlite_root "${CMAKE_CURRENT_SOURCE_DIR}/../build/deps/astra/sqlite/3.53.4")
set(star_sqlite_source "${star_sqlite_root}/sqlite-amalgamation-3530400")
if(NOT EXISTS "${ASTRA_SQLITE_ARCHIVE}")
    message(FATAL_ERROR "Missing approved SQLite archive: ${ASTRA_SQLITE_ARCHIVE}; no implicit download is allowed")
endif()
file(SHA256 "${ASTRA_SQLITE_ARCHIVE}" star_sqlite_hash)
if(NOT star_sqlite_hash STREQUAL "1e71ddf93849c6a6ecf58b827c0692073d2dd7ee40196158068f7b29f422e87d")
    message(FATAL_ERROR "SQLite 3.53.4 archive SHA256 mismatch")
endif()
if(NOT EXISTS "${star_sqlite_source}")
    file(MAKE_DIRECTORY "${star_sqlite_root}")
    file(ARCHIVE_EXTRACT INPUT "${ASTRA_SQLITE_ARCHIVE}" DESTINATION "${star_sqlite_root}")
endif()
# 不覆盖已解包的第三方代码; 内容不符时明确失败, 防止复用被修改或不完整的缓存.
foreach(part IN ITEMS c h)
    if(NOT EXISTS "${star_sqlite_source}/sqlite3.${part}")
        message(FATAL_ERROR "Incomplete SQLite source cache: ${star_sqlite_source}")
    endif()
    file(SHA256 "${star_sqlite_source}/sqlite3.${part}" star_sqlite_hash)
    if(part STREQUAL "c")
        set(star_sqlite_expected "b1dd5d74ec7f29055a6684fa06fb3c2f6821c87dd38f9a458dfd2e8a1db28189")
    else()
        set(star_sqlite_expected "919e7f2e8ed1d8f56ac17b412b8971c76aa5d1a879752cc6058f75e7d5910e1d")
    endif()
    if(NOT star_sqlite_hash STREQUAL star_sqlite_expected)
        message(FATAL_ERROR "SQLite source SHA256 mismatch: sqlite3.${part}")
    endif()
endforeach()
add_library(star_sqlite STATIC "${star_sqlite_source}/sqlite3.c")
set_target_properties(star_sqlite PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)
target_include_directories(star_sqlite SYSTEM PUBLIC "${star_sqlite_source}")
target_compile_definitions(star_sqlite PRIVATE SQLITE_THREADSAFE=1 SQLITE_OMIT_LOAD_EXTENSION=1 SQLITE_DQS=0 SQLITE_DEFAULT_MEMSTATUS=0)
target_link_libraries(star_sqlite PRIVATE Threads::Threads m)
# 使用 C 编译器, 不继承手写 C++ 反射/契约或 -Werror, Sanitizer 则覆盖实际数据库访问.
if(ASTRA_SANITIZER)
    target_compile_options(star_sqlite PRIVATE "-fsanitize=${ASTRA_SANITIZER}" -fno-omit-frame-pointer)
endif()
