function(verdandi_embed_protocol output_variable)
    set(protocol_root "${CMAKE_CURRENT_SOURCE_DIR}/src/protocol")
    foreach(domain IN ITEMS registration catalog)
        if(domain STREQUAL "registration")
            set(operations register update renew unregister)
        else()
            set(operations read replace patch delete)
        endif()
        foreach(operation IN LISTS operations)
            string(TOUPPER "${domain}_${operation}" variable)
            file(READ "${protocol_root}/${domain}/${operation}.lua" "${variable}_LUA")
        endforeach()
    endforeach()

    set(generated_directory "${CMAKE_CURRENT_BINARY_DIR}/generated")
    file(MAKE_DIRECTORY "${generated_directory}")
    set(generated_source "${generated_directory}/protocol.cpp")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/protocol.cpp.in" "${generated_source}" @ONLY)
    set(${output_variable} "${generated_source}" PARENT_SCOPE)
endfunction()
