-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 LaconisIves
--
-- Code generated by testkit/lua/generate_registration.py; DO NOT EDIT.
-- Verdandi Registration update script.
--
-- KEYS[1]：verdandi:registration:<zone>:<type>:<uuid>，保存完整 Registration Hash。
-- KEYS[2]：verdandi:registry:<zone>:<type>，同时作为成员索引 Hash 和事件频道。
-- ARGV[1..3]：uuid、revision、version（不修改时为空）；ARGV[4..]：Data 字段名和值的有序键值对。
--
-- SDK 负责请求校验和应用数据解码；脚本只把一次已校验的 Registration 操作
-- 粘合为一次 Redis 原子变更。Attr 和 Data 字节对 Redis/Lua 始终不透明。

-- BEGIN common/bindings.lua.inc
-- 缓存每条热路径都会反复使用的运行时函数、参数表和 key，避免重复全局/表查找。
local redis_call = redis.call
local to_number = tonumber
-- arguments 是当前命令完整 ARGV；action fragment 按固定位置解释控制字段和用户字段键值对。
local arguments = ARGV
-- registration_key 保存一个进程内 Registration 的完整 Hash；registry_key 保存同 zone/type 的成员 revision 并兼作 Pub/Sub channel。
local registration_key = KEYS[1]
local registry_key = KEYS[2]
-- END common/bindings.lua.inc

-- BEGIN actions/update.lua.inc
-- Update 只比较 Redis 管理的 revision，再原子安装 SDK 已校验的 Data patch 并刷新租约。
-- arguments[1..3] 分别为 uuid、新 revision、version（不修改时为空），arguments[4..] 是已排序的局部 Data 键值对。
local uuid = arguments[1]
local revision_value = arguments[2]
local version_value = arguments[3]
local revision = to_number(revision_value)

-- timestamp/ttl 仅用于刷新租约；它们不是 Update 的用户可修改字段。
local state = redis_call(
    "HMGET", registration_key, "@revision", "@timestamp", "@ttl"
)
local stored_revision = state[1]
if not stored_revision then
    return { "&result", "error", "&status", "missing" }
end
local current_revision = to_number(stored_revision)
local current_timestamp = to_number(state[2])
local current_ttl = to_number(state[3])
if not current_revision or not current_timestamp or not current_ttl then
    return { "&result", "error", "&status", "corrupt" }
end

-- 热路径期望 revision 恰好递增一，仅用一次不等比较进入冲突分支。
if revision ~= current_revision + 1 then
    if revision == current_revision then
        return {
            "&result", "ok",
            "@revision", current_revision,
            "@timestamp", current_timestamp,
        }
    end
    if revision < current_revision then
        return {
            "&result", "error",
            "&status", "stale",
            "&field", "@revision",
            "@revision", current_revision,
        }
    end
    return {
        "&result", "error",
        "&status", "transition",
        "&field", "@revision",
        "@revision", current_revision,
    }
end

-- Redis TIME 是租约权威时钟；保留记录中更大的 timestamp 可防止 Redis 时间短暂回拨缩短租约。
local redis_time = redis_call("TIME")
local timestamp = to_number(redis_time[1]) * 1000 +
    math.floor(to_number(redis_time[2]) / 1000)
if current_timestamp > timestamp then
    timestamp = current_timestamp
end
local deadline = timestamp + current_ttl
if deadline > 70368744177663 then
    return {
        "&result", "error",
        "&status", "invalid",
        "&field", "@ttl",
    }
end

-- Update 事件只携带索引、时间、revision、可选 version 和本次局部 Data patch。
local event = {
    "&protocol", "v1",
    "&kind", "update",
    "@uuid", uuid,
    "@revision", revision,
    "@timestamp", timestamp,
}
local event_index = 11
if version_value ~= "" then
    event[11] = "@version"
    event[12] = to_number(version_value)
    event_index = 13
end
for index = 4, #arguments, 2 do
    event[event_index] = arguments[index]
    event[event_index + 1] = arguments[index + 1]
    event_index = event_index + 2
end
local encoded_event = cmsgpack.pack(event)

-- version 未变化时不写 @version，减少一个 Hash field 参数和一次内部字段覆盖。
if version_value == "" then
    redis_call(
        "HSET", registration_key,
        "@revision", revision_value,
        "@timestamp", timestamp,
        unpack(arguments, 4)
    )
else
    redis_call(
        "HSET", registration_key,
        "@revision", revision_value,
        "@timestamp", timestamp,
        "@version", version_value,
        unpack(arguments, 4)
    )
end
-- Data patch、Hash TTL、成员 field TTL 和 Pub/Sub 事件在一个脚本中原子提交。
redis_call("PEXPIREAT", registration_key, deadline)
redis_call(
    "HSETEX", registry_key, "PXAT", deadline,
    "FIELDS", 1, uuid, revision_value
)
redis_call("PUBLISH", registry_key, encoded_event)
return { "&result", "ok", "@revision", revision, "@timestamp", timestamp }
-- END actions/update.lua.inc

