-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 LaconisIves
--
-- Code generated by testkit/lua/generate_catalog.py; DO NOT EDIT.
-- Verdandi Catalog delete script.
--
-- KEYS[1]: verdandi:catalog:<zone>:@meta
-- KEYS[2]: verdandi:catalog:<zone>:@live
-- KEYS[3]: verdandi:catalog:<zone>:@deleted
-- KEYS[4]: verdandi:catalog:<zone>:@deleted_time
-- KEYS[5]: verdandi:catalog:<zone>:<part>:<id>
-- KEYS[6]: verdandi:catalog:<zone>:<part>:<id>:@field_revisions
-- ARGV: path-member.
--
-- SDKs own application encoding, path and shape validation, capacity
-- projection, and notification decoding. Lua only joins current-state
-- preconditions with an accepted mutation or read snapshot atomically.

-- BEGIN common/bindings.lua.inc
local redis_call = redis.call

local function redis_type(key)
    local result = redis_call("TYPE", key)
    if type(result) == "table" then
        return result.ok
    end
    return result
end

local function error_reply(status, field, revision)
    local result = { "&result", "error", "&status", status }
    if field then
        result[#result + 1] = "&field"
        result[#result + 1] = field
    end
    if revision then
        result[#result + 1] = "@revision"
        result[#result + 1] = revision
    end
    return result
end
-- END common/bindings.lua.inc

-- BEGIN common/integer.lua.inc
local maximum_revision = "9007199254740991"
local maximum_encoded_bytes = 4194304
local maximum_fields = 65536

local function canonical_nonnegative(value)
    if value == "0" then
        return true
    end
    if not value or not string.match(value, "^[1-9][0-9]*$") then
        return false
    end
    return #value < #maximum_revision or
        (#value == #maximum_revision and value <= maximum_revision)
end

local function canonical_positive(value)
    return value ~= "0" and canonical_nonnegative(value)
end

local function decimal_less(left, right)
    if #left ~= #right then
        return #left < #right
    end
    return left < right
end

local function increment_decimal(value)
    local length = #value
    local index = length
    while index > 0 and string.byte(value, index) == 57 do
        index = index - 1
    end
    if index == 0 then
        return "1" .. string.rep("0", length)
    end
    return string.sub(value, 1, index - 1) ..
        string.char(string.byte(value, index) + 1) ..
        string.rep("0", length - index)
end

local function canonical_count(value, maximum)
    if value ~= "0" and
        (not value or not string.match(value, "^[1-9][0-9]*$")) then
        return nil
    end
    local result = tonumber(value)
    if not result or result > maximum or result % 1 ~= 0 then
        return nil
    end
    return result
end
-- END common/integer.lua.inc

-- BEGIN common/state.lua.inc
local meta_key = KEYS[1]
local live_key = KEYS[2]
local deleted_key = KEYS[3]
local deleted_time_key = KEYS[4]
local catalog_key = KEYS[5]
local field_revisions_key = KEYS[6]
local member = ARGV[1]

if #KEYS ~= 6 or #ARGV < 1 or not member or member == "" then
    return error_reply("contract")
end

local fail = error_reply

local meta_type = redis_type(meta_key)
local live_type = redis_type(live_key)
local deleted_type = redis_type(deleted_key)
local deleted_time_type = redis_type(deleted_time_key)
local catalog_type = redis_type(catalog_key)
local field_revision_type = redis_type(field_revisions_key)
if (meta_type ~= "none" and meta_type ~= "hash") or
    (live_type ~= "none" and live_type ~= "zset") or
    (deleted_type ~= "none" and deleted_type ~= "zset") or
    (deleted_time_type ~= "none" and deleted_time_type ~= "zset") or
    (catalog_type ~= "none" and catalog_type ~= "hash") or
    (field_revision_type ~= "none" and field_revision_type ~= "zset") then
    return fail("corrupt")
end

local meta = redis_call("HMGET", meta_key, "@revision", "@floor_revision")
local global_revision = meta[1]
local floor_revision = meta[2]
if not global_revision then
    if floor_revision or redis_call("HLEN", meta_key) ~= 0 or
        redis_call("ZCARD", live_key) ~= 0 or
        redis_call("ZCARD", deleted_key) ~= 0 or
        redis_call("ZCARD", deleted_time_key) ~= 0 then
        return fail("corrupt")
    end
    global_revision = "0"
    floor_revision = "0"
elseif not canonical_positive(global_revision) or
    not canonical_nonnegative(floor_revision) or
    decimal_less(global_revision, floor_revision) then
    return fail("corrupt")
end

local live_revision = redis_call("ZSCORE", live_key, member)
local deleted_revision = redis_call("ZSCORE", deleted_key, member)
local deleted_time = redis_call("ZSCORE", deleted_time_key, member)
if (live_revision and deleted_revision) or
    ((deleted_revision and not deleted_time) or
        (deleted_time and not deleted_revision)) or
    (live_revision and not canonical_positive(live_revision)) or
    (deleted_revision and not canonical_positive(deleted_revision)) or
    (deleted_time and not canonical_nonnegative(deleted_time)) then
    return fail("corrupt")
end

local current_revision = "0"
local current_kind = nil
local current_encoded_bytes = "0"
local current_replace_revision = "0"

if catalog_type == "hash" then
    if not live_revision or deleted_revision then
        return fail("corrupt")
    end
    local header = redis_call(
        "HMGET", catalog_key,
        "@revision", "@replace_revision", "@kind", "@encoded_bytes"
    )
    current_revision = header[1]
    current_replace_revision = header[2]
    current_kind = header[3]
    current_encoded_bytes = header[4]
    if not canonical_positive(current_revision) or
        not canonical_positive(current_replace_revision) or
        decimal_less(current_revision, current_replace_revision) or
        (current_kind ~= "value" and current_kind ~= "array" and
            current_kind ~= "map") or
        not canonical_nonnegative(current_encoded_bytes) or
        tonumber(current_encoded_bytes) > maximum_encoded_bytes or
        live_revision ~= current_revision then
        return fail("corrupt")
    end
    if field_revision_type == "none" and redis_call("HLEN", catalog_key) ~= 4 then
        return fail("corrupt")
    end
elseif live_revision or field_revision_type == "zset" then
    return fail("corrupt")
elseif deleted_revision then
    current_revision = deleted_revision
end

if decimal_less(global_revision, current_revision) then
    return fail("corrupt")
end
-- END common/state.lua.inc

-- BEGIN actions/delete.lua.inc
if #ARGV ~= 1 then
    return fail("contract")
end
if global_revision == maximum_revision then
    return fail("capacity", "@revision")
end

local retention_milliseconds = 86400000
local retention_count = 1000000
local prune_batch = 256
local next_revision = increment_decimal(global_revision)
local now = redis_call("TIME")
local now_milliseconds = tonumber(now[1]) * 1000 +
    math.floor(tonumber(now[2]) / 1000)

redis_call("UNLINK", catalog_key, field_revisions_key)
redis_call("ZREM", live_key, member)
redis_call("ZADD", deleted_key, next_revision, member)
redis_call("ZADD", deleted_time_key, now_milliseconds, member)

local evicted = {}
local selected = {}
local cutoff = now_milliseconds - retention_milliseconds
local expired = redis_call(
    "ZRANGEBYSCORE", deleted_time_key, "-inf", cutoff,
    "LIMIT", 0, prune_batch
)
for index = 1, #expired do
    local candidate = expired[index]
    if candidate ~= member and not selected[candidate] then
        selected[candidate] = true
        evicted[#evicted + 1] = candidate
    end
end

local excess = redis_call("ZCARD", deleted_key) - retention_count
local required = math.min(
    math.max(excess - #evicted, 0),
    prune_batch - #evicted
)
if required > 0 then
    local candidates = redis_call(
        "ZRANGE", deleted_key, 0, prune_batch * 2 - 1
    )
    for index = 1, #candidates do
        local candidate = candidates[index]
        if candidate ~= member and not selected[candidate] then
            selected[candidate] = true
            evicted[#evicted + 1] = candidate
            required = required - 1
            if required == 0 then
                break
            end
        end
    end
end

local next_floor = floor_revision
if #evicted > 0 then
    local revisions = redis_call("ZMSCORE", deleted_key, unpack(evicted))
    for index = 1, #revisions do
        local candidate_revision = revisions[index]
        if candidate_revision and decimal_less(next_floor, candidate_revision) then
            next_floor = candidate_revision
        end
    end
    redis_call("ZREM", deleted_key, unpack(evicted))
    redis_call("ZREM", deleted_time_key, unpack(evicted))
end

redis_call("HSET", meta_key, "@revision", next_revision,
    "@floor_revision", next_floor)
redis_call("PUBLISH", catalog_key, cmsgpack.pack({
    "v1", "delete", member, next_revision
}))
return {
    "&result", "ok",
    "@revision", next_revision,
    "@floor_revision", next_floor,
    "@pruned", tostring(#evicted),
}
-- END actions/delete.lua.inc

