// Code generated by verdandi-refgen; DO NOT EDIT.

package refexample

import verdandiregistration "github.com/eosforge/verdandi/sdk/go/registration"

// ProxyAttrRef 是 ProxyAttr 的回调期只读视图；不得在选择回调结束后保留。
type ProxyAttrRef struct {
	fieldCertificate verdandiregistration.ReferenceSlice[Certificate, byte]
	fieldEndpoint    string
}

// Certificate 返回 ProxyAttr.Certificate；引用型字段会返回独立副本。
func (view ProxyAttrRef) Certificate() Certificate {
	return view.fieldCertificate.Clone()
}

// Endpoint 返回 ProxyAttr.Endpoint；引用型字段会返回独立副本。
func (view ProxyAttrRef) Endpoint() string {
	return view.fieldEndpoint
}

// ProxyDataRef 是 ProxyData 的回调期只读视图；不得在选择回调结束后保留。
type ProxyDataRef struct {
	fieldPayload verdandiregistration.ReferenceSlice[[]byte, byte]
	fieldPower   int64
	fieldReady   bool
}

// Payload 返回 ProxyData.Payload；引用型字段会返回独立副本。
func (view ProxyDataRef) Payload() []byte {
	return view.fieldPayload.Clone()
}

// Power 返回 ProxyData.Power；引用型字段会返回独立副本。
func (view ProxyDataRef) Power() int64 {
	return view.fieldPower
}

// Ready 返回 ProxyData.Ready；引用型字段会返回独立副本。
func (view ProxyDataRef) Ready() bool {
	return view.fieldReady
}

// ProxyDataEditor 通过字段 setter 修改所选 ProxyData 的本地预测副本。
type ProxyDataEditor struct {
	editor verdandiregistration.ReferenceEditor[ProxyAttr, ProxyData]
}

// SetPayload 暂存 ProxyData.Payload；只有最终选中且回调成功才提交。
func (editor ProxyDataEditor) SetPayload(value []byte) error {
	return editor.editor.Apply(func(target *ProxyData) {
		if value == nil {
			target.Payload = nil
			return
		}
		target.Payload = append([]byte{}, value...)
	})
}

// SetPower 暂存 ProxyData.Power；只有最终选中且回调成功才提交。
func (editor ProxyDataEditor) SetPower(value int64) error {
	return editor.editor.Apply(func(target *ProxyData) {
		target.Power = value
	})
}

// SetReady 暂存 ProxyData.Ready；只有最终选中且回调成功才提交。
func (editor ProxyDataEditor) SetReady(value bool) error {
	return editor.editor.Apply(func(target *ProxyData) {
		target.Ready = value
	})
}

// ProxyReferenceCandidates 是代码生成的回调期候选集合。
type ProxyReferenceCandidates = verdandiregistration.ReferenceCandidates[
	ProxyAttr,
	ProxyData,
	ProxyAttrRef,
	ProxyDataRef,
	ProxyDataEditor,
]

// ProxyReferenceCandidate 是代码生成的回调期只读候选。
type ProxyReferenceCandidate = verdandiregistration.ReferenceCandidate[
	ProxyAttr,
	ProxyData,
	ProxyAttrRef,
	ProxyDataRef,
	ProxyDataEditor,
]

// ProxyReferenceSelection 是可由策略返回并按需编辑的候选。
type ProxyReferenceSelection = verdandiregistration.ReferenceSelection[
	ProxyAttr,
	ProxyData,
	ProxyAttrRef,
	ProxyDataRef,
	ProxyDataEditor,
]

// ProxyReferenceSelector 嵌入 Verdandi 引用型热路径，并保留其 WithOne/WithAny API。
type ProxyReferenceSelector struct {
	*verdandiregistration.ReferenceSelector[
		ProxyAttr,
		ProxyData,
		ProxyAttrRef,
		ProxyDataRef,
		ProxyDataEditor,
	]
}

// NewProxyReferenceSelector 把普通强类型 Selector 包装为生成的引用型入口。
func NewProxyReferenceSelector(
	selector *verdandiregistration.Selector[ProxyAttr, ProxyData],
) (*ProxyReferenceSelector, error) {
	core, err := verdandiregistration.NewReferenceSelector(
		selector,
		verdandiregistration.ReferenceSchema[ProxyAttr, ProxyData, ProxyAttrRef, ProxyDataRef, ProxyDataEditor]{
			Attr: func(value *ProxyAttr) ProxyAttrRef {
				return ProxyAttrRef{
					fieldCertificate: verdandiregistration.NewReferenceSlice(value.Certificate),
					fieldEndpoint:    value.Endpoint,
				}
			},
			Data: func(value *ProxyData) ProxyDataRef {
				return ProxyDataRef{
					fieldPayload: verdandiregistration.NewReferenceSlice(value.Payload),
					fieldPower:   value.Power,
					fieldReady:   value.Ready,
				}
			},
			Edit: func(editor verdandiregistration.ReferenceEditor[ProxyAttr, ProxyData]) ProxyDataEditor {
				return ProxyDataEditor{editor: editor}
			},
			CloneData: func(value ProxyData) ProxyData {
				if value.Payload != nil {
					value.Payload = append([]byte{}, value.Payload...)
				}
				return value
			},
		},
	)
	if err != nil {
		return nil, err
	}
	return &ProxyReferenceSelector{ReferenceSelector: core}, nil
}
